### ISSUE TITLE
SCRIPT1004: Expected ';'

### ISSUE THREAD

**Issue by chensiel** [Basaingeal/Razor.Clipboard#223]
There is an error in IE11 .
SCRIPT1004: Expected ';'
clipboard.min.js (1,1241)

**Comment by Basaingeal** [comment]
This library wraps the newer browser Clipboard API. This API isn't supported by IE11, and so this library doesn't support IE11. The error you're seeing is actually a result of the code not being transpiled to a version of JavaScript that IE11 understands, because IE11 support is not being considered.

https://github.com/Basaingeal/Razor.Clipboard#compatibility
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard#Browser_compatibility
